UPDATE sensor_staging_table
SET TIMESTAMP = TO_TIMESTAMP(REPLACE(TIMESTAMP, '"', ''), 'YYYY-MM-DD HH24:MI:SS');

UPDATE crop_staging_table
SET TIMESTAMP = TO_TIMESTAMP(TIMESTAMP, 'MM/DD/YYYY HH24:MI');

UPDATE pest_staging_table
SET TIMESTAMP = TO_TIMESTAMP(TIMESTAMP, 'MM/DD/YYYY HH24:MI');

UPDATE soil_staging_table
SET TIMESTAMP = TO_TIMESTAMP(TIMESTAMP, 'MM/DD/YYYY HH24:MI');

UPDATE weather_staging_table
SET TIMESTAMP = TO_TIMESTAMP(TIMESTAMP, 'MM/DD/YYYY HH24:MI');