-- Update NULL values in AGRICULTURAL_PERFORMANCE_FACT for PEST_TYPE
UPDATE AGRICULTURAL_PERFORMANCE_FACT
SET PEST_TYPE = 'Unknown'
WHERE PEST_TYPE IS NULL;

-- Update NULL values in other tables for corresponding columns
UPDATE CROP_DIMENSION
SET CROP_TYPE = 'Unknown'
WHERE CROP_TYPE IS NULL;

UPDATE SOIL_DIMENSION
SET SOIL_MOISTURE = 0,
    SOIL_PH = 0,
    NITROGEN_LEVEL = 0,
    PHOSPHORUS_LEVEL = 0,
    ORGANIC_MATTER = 0
WHERE SOIL_MOISTURE IS NULL;

UPDATE SENSOR_DIMENSION
SET TEMPERATURE = 0,
    HUMIDITY = 0,
    SOIL_MOISTURE = 0,
    lIGHT_INTENSITY = 0,
    BATTERY_LEVEL = 0
WHERE TEMPERATURE IS NULL;

UPDATE PEST_DIMENSION
SET PEST_TYPE = 'Unknown',
    PEST_DESCRIPTION = 'Unknown',
    PEST_SEVERITY = 'Unknown'
WHERE PEST_TYPE IS NULL;

-- Update NULL values in WEATHER_DIMENSION for PRECIPITATION
UPDATE WEATHER_DIMENSION
SET PRECIPITATION = 0,
    WIND_SPEED = 0
WHERE PRECIPITATION IS NULL;
